
    Vagrant.configure('2') do |config|
        config.vm.define 'sebas2' do |vm|
            vm.vm.box = 'ubuntu/bionic64'
            vm.vm.provider 'virtualbox' do |vb|
                vb.memory = '2048'
                vb.cpus = '2'
                vb.customize ['createhd', '--filename', 'storage.vdi', '--size', '20'] // Usar el tamaño de almacenamiento calculado
                vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'storage.vdi']
            end
        end
    end
    