
        Vagrant.configure('2') do |config|
            config.vm.define 'Pruebas123' do |vm|
                vm.vm.box = 'ubuntu/bionic64'
                vm.vm.network 'public_network', bridge: true
                vm.vm.provider 'virtualbox' do |v|
                    v.memory = '2080'
                    v.cpus = '2'
                    unless File.exist?('#{ storage.vdi }')
                        v.customize ['createhd', '--filename', '#{ storage.vdi }', '--size', '#{ 10240 }']
                    end
                    v.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 0, '--device', 0, '--type', 'hdd', '--medium', '#{ storage.vdi }']
                end
            end
        end
        