
        Vagrant.configure('2') do |config|
            config.vm.define 'sebas312321312321123' do |vm|
                vm.vm.box = 'ubuntu/bionic64'
                vm.vm.network 'public_network', bridge: true
                vm.vm.provider 'virtualbox' do |v|
                    v.memory = '2080'
                    v.cpus = '4'
                    v.customize ['createhd', '--filename', 'storage.vdi', '--size', 10240]
                    v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 0, '--device', 0, '--type', 'hdd', '--medium', 'storage.vdi']
                end
            end
        end
        