
Vagrant.configure('2') do |config|
    config.vm.define 'Ubuntu' do |vm|
        vm.vm.box = 'ubuntu/bionic64'
        vm.vm.network 'public_network', bridge: 'en0: Wi-Fi (AirPort)' // Única interfaz en modo bridge
        vm.vm.provider 'virtualbox' do |vb|
            vb.memory = '2080'
            vb.cpus = '2'
            unless File.exist?('#{ storage.vdi }')
                vb.customize ['createhd', '--filename', '#{ storage.vdi }', '--size', '#{ 10240 }']
            end
            vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', '#{ storage.vdi }']
        end
        vm.vm.provision 'shell', inline: <<-SHELL
            # Crear el usuario 'emergentes' y establecer la contraseña
            useradd -m emergentes
            echo 'emergentes:emergentes' | chpasswd

            # Verificar si el usuario se creó correctamente
            id emergentes

            # Crear el archivo /etc/motd con las credenciales
            echo 'Welcome to your VM!' > /etc/motd
            echo 'Username: emergentes' >> /etc/motd
            echo 'Password: emergentes' >> /etc/motd

            # Asegurarse de que el archivo /etc/motd tenga los permisos correctos
            chmod 644 /etc/motd

            # Mostrar el contenido del archivo /etc/motd para verificación
            cat /etc/motd
        SHELL
    end
end
