
        Vagrant.configure('2') do |config|
            config.vm.define 'VMWARE PRUEBA' do |vm|
                vm.vm.box = 'ubuntu/bionic64'
                vm.vm.network 'public_network', bridge: 'en0: Wi-Fi (AirPort)' # Primera interfaz en modo bridge
                vm.vm.network 'public_network', bridge: 'en0: Wi-Fi (AirPort)' # Segunda interfaz en modo bridge
                vm.vm.provider 'vmware_workstation' do |v|
                    v.vmx['memsize'] = '2080'
                    v.vmx['numvcpus'] = '2'
                    v.vmx['displayName'] = 'VMWARE PRUEBA'
                    v.vmx['scsi0:0.fileName'] = 'storage.vmdk'
                    v.vmx['scsi0:0.present'] = 'TRUE'
                    v.vmx['scsi0:0.deviceType'] = 'scsi-hardDisk'
                    v.vmx['scsi0:0.mode'] = 'persistent'
                    v.vmx['scsi0:0.redo'] = ''
                    # Configuración adicional para el disco duro puede ser necesaria aquí
                end
            end
        end
        