
    Vagrant.configure('2') do |config|
        config.vm.define 'seaasdsadad' do |vm|
            vm.vm.box = 'ubuntu/bionic64'
            vm.vm.network 'public_network', bridge: true
            vm.vm.provider 'virtualbox' do |v|
                v.memory = '2080'
                v.cpus = '2'
            end
        end
    end
    