
Vagrant.configure('2') do |config|
    config.vm.define 'PruebaDisk2' do |vm|
        vm.vm.box = 'ubuntu/bionic64'
        vm.vm.provider 'virtualbox' do |vb|
            vb.memory = '2048'
            vb.cpus = '4'
            unless File.exist?('#{ storage.vdi }')
                vb.customize ['createhd', '--filename', '#{ storage.vdi }', '--size', '#{ 20480 }']
            end
            vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', '#{ storage.vdi }']
        end
    end
end
