
        Vagrant.configure('2') do |config|
            config.vm.define 'PIEDRA' do |vm|
                vm.vm.box = 'ubuntu/bionic64'
                vm.vm.network 'public_network', bridge: 'en0: Wi-Fi (AirPort)' # Primera interfaz en modo bridge
                vm.vm.network 'public_network', bridge: 'en0: Wi-Fi (AirPort)' # Segunda interfaz en modo bridge
                vm.vm.provider 'vmware_desktop' do |v|
                    v.vmx['memsize'] = '2080'
                    v.vmx['numvcpus'] = '2'
                    v.vmx['displayName'] = 'PIEDRA'
                    # Configuración adicional para el disco duro puede ser necesaria aquí
                end
            end
        end
        